apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-server.fullname" . }}-service
  labels:
    app: {{ include "mcp-server.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "mcp-server.name" . }}
